// Lignes source synthétiques (une par table Intervention/Site/...), utilisées uniquement
// pour valider localement la forme des modules de mapping (pas de vraies données).
export const FIXTURES = {
  marques: { nummar: 1, nommar: 'Daikin' },
  reperes: { id: 1, Repere: 'CL1', CtrlEtancheite: 1 },
  types_telecommande: { id: 1, TypeTelecommande: 'Filaire' },
  jours_feries: { datjoufer: new Date(Date.UTC(2026, 0, 1)) },
  types_evenement_vehicule: { Numero: 1, Evenement_Vehicule: 'Releve KM' },
  etats_vehicule: { Numero: 0, EtatVehicule: 'En service' },
  references_materiel: {
    id: 1,
    Reference: 'REF-1',
    Repere: 'CL1',
    Type: 'Split',
    Nommar: 'Daikin',
    Fluide: 'R32',
    TypeTel: 'Filaire',
    Reversible: 'OUI',
    Resistance: 'NON',
    PuissanceFrigo: '5.5',
    PuissanceCalo: 'NC',
    QteGaz: '1.2',
    NbFiltres: '2',
    DimFiltres: '30x30',
    NbCourroies: null,
    RefCourroies: null,
    AppointRoof: null,
  },
  clients: {
    numcli: 1,
    nomcli: 'Client Test',
    adrcli: '1 rue Test',
    codposcli: '33000',
    vilcli: 'Bordeaux',
    telcli: '0500000000',
    faxcli: null,
    concli: 'M. Test',
    melcli: 'test@example.com',
    hormaxintcli: 24,
    cheminpho: 'ESAB1',
    cheminpla: 'ESAB2',
    affcli: 1,
    coutheuremainoeuvre: 45.5,
    coutdeplacement: 20,
  },
  donneurs_ordre: {
    donneurid: 1,
    nomdonneur: 'Donneur Test',
    adrdonneur: null,
    codposdonneur: null,
    vildonneur: null,
    teldonneur: null,
    faxdonneur: null,
    condonneur: null,
    meldonneur: 'pied1',
    hormaxintdonneur: 48,
    cheminpho: 'logo.png',
    cheminpla: 'pied3',
    affdonneur: 1,
    sairapdonneur: 0,
  },
  intervenants: {
    numintervenant: 1,
    codint: 'FMC',
    nomint: 'FMC',
    adrint: null,
    codposint: null,
    vilint: null,
    telint: null,
    faxint: null,
    adrmelint: null,
    NomDirigeant_Interv: null,
    TelDirigeant_Interv: null,
    Mail_Dirigeant_Interv: null,
    NomInterlocuteur_Interv: null,
    TelInterlocuteur_Interv: null,
    Info_Interv: null,
    Histo_FMC_Interv: null,
    VillesInterventions_Interv: null,
    Latitude_Interv: 44.8,
    Longitude_Interv: -0.5,
    PrecisionGeo_Interv: 'ROOFTOP',
    Provenance_Interv: null,
    IndMaint_Interv: 5,
    Ind_Depann_Interv: 5,
    Ind_Travaux_Interv: 5,
    Ind_React_Interv: 5,
    DossierOrdi_Interv: null,
    TexteNeplusInterv: null,
    EstTech: 1,
    NePlusIntervenir: 0,
    Status_Prospect: 0,
    Status_ST_FMC: 0,
    Status_ST_FMC_Ponctuel: 0,
    Status_Act_Poss_Maint: 1,
    Status_Act_Poss_Depan: 1,
    Status_Act_Poss_Travaux: 1,
    Status_Act_Donn_Maint: 0,
    Status_Act_Donn_Depan: 0,
    Status_Act_Donn_Travaux: 0,
    Zone_Nationale: 1,
    MailFacturation: null,
    SiteInternet: null,
    ExistePlus: 0,
    AutoLiquidation: 0,
  },
  intervenant_zones: { numintervenant: 1, numzonint: 63, numzonint_2_Interv: null, numzonint_3_Interv: null, numzonint_4_Interv: null },
  intervenant_activites: {
    numintervenant: 1,
    Activite_1: 1, MO_Activite_1: 40, Depl_Activite_1: 15, Date_Activite_1: new Date(Date.UTC(2020, 0, 1)),
    Activite_2: null, MO_Activite_2: null, Depl_Activite_2: null, Date_Activite_2: null,
    Activite_3: null, MO_Activite_3: null, Depl_Activite_3: null, Date_Activite_3: null,
    Activite_4: null, MO_Activite_4: null, Depl_Activite_4: null, Date_Activite_4: null,
    Activite_5: null, MO_Activite_5: null, Depl_Activite_5: null, Date_Activite_5: null,
    Activite_6: null, MO_Activite_6: null, Depl_Activite_6: null, Date_Activite_6: null,
  },
  utilisateurs: {
    numuti: 1,
    nomuti: 'Dupont',
    preuti: 'Jean',
    loguti: 'jdupont',
    codintuti: 'FMC',
    typuti: 1,
    nomsocuti: 'FMC Bureau',
    numsoc: 113,
    Mail: 'jdupont@example.com',
    KmARenseigner: 0,
    Immat: null,
  },
  intervenants_fk_utilisateurs: { numintervenant: 1, ChargeAffaireFMC_Interv: 1, CreePar_Interv: 1 },
  contacts: {
    codcon: 'C1',
    nomcon: 'Martin',
    precon: 'Paul',
    numcli: 1,
    adrmelcon: null,
    telcon: null,
    faxcon: null,
    mobcon: null,
    obscon: null,
    foncon: null,
    civcon: 'M.',
    numdonneur: null,
  },
  sites: {
    cptsit: 1,
    numsit: 100,
    numcli: 1,
    codsit: 'S100',
    nomsit: 'Magasin Test',
    nomsocsit: null,
    sitsit: 'centre-ville',
    typsit: 'H',
    adrsit: '2 rue Test',
    codpossit: '33000',
    vilsit: 'Bordeaux',
    telsit: null,
    faxsit: null,
    melsti: null,
    civres: null,
    nomres: null,
    preres: null,
    telcencom: null,
    numzonsit: 63,
    numzone2: null,
    numintervenant: 1,
    donneurid: 1,
    surven: 500,
    surtot: 800,
    nbrentsit: 4,
    nbrdesenfsit: 1,
    datdervisdes: new Date(Date.UTC(2024, 5, 1)),
    comsit: null,
    commentaire: null,
    InfosCompl: null,
    Invest: 0,
    datcresit: '01/01/2010',
    demixasit: 0,
    indclitec: 1,
    indvetust: 2,
    indpuissance: 3,
    indaccessib: 4,
    nbrplan: 0,
    nbrpho: 0,
    allumageclim: 0,
    domotique: 0,
    accessfiltre: 0,
    datprisencharge: new Date(Date.UTC(2010, 0, 1)),
    misajoursecurite: 0,
    aspirateur: 0,
    typfluid: 6,
    temp_entree: '20',
    temp_sortie: '12',
    longitude: -0.5,
    latitude: 44.8,
    precisiongeo: 'ROOFTOP',
    chemindoc: null,
    datemiseenservicesite: new Date(Date.UTC(2010, 0, 1)),
    garantiepiecesmainoeuvre: 2,
    garantiepieces: 2,
    garantiecompresseur: 5,
    datedernierevisiteentretien: new Date(Date.UTC(2025, 5, 1)),
    photoafaire: 0,
    photofaite: 1,
    auditafaire: 0,
    auditfait: 1,
    controleetancheiteafaire: 0,
    controleetancheitefait: 1,
    controleetancheiteponctuel: 0,
    Mess_Devis: null,
    NumEsabora: null,
    AvecPrixSite: 0,
    PrixMo: null,
    PrixDepl: null,
    RDV_Prendre: 0,
    fermeture: 0,
    datefermeture: null,
    motiffermeture: null,
    majregistresecuritefait: 0,
    majregistresecuriteafaire: 0,
    creele: new Date(Date.UTC(2010, 0, 1)),
    majle: new Date(Date.UTC(2025, 5, 1)),
  },
  site_contrats: {
    cptsit: 1,
    numerocontratclient: 'CTR1',
    datprisencharge: new Date(Date.UTC(2010, 0, 1)),
    nbrentsit: 4,
    mntredev: 1000,
    montantredevancetechnique: null,
    montantredevancefiltre: 200,
    nombrevisitefiltre: 2,
    nombrevisitetechnique: 4,
    NumSousTraitClim: 1,
    TarifSousTraitClim: 30,
    datesignaturecontrat: new Date(Date.UTC(2010, 0, 1)),
    NumContratChaudiere: null,
    DateContratChaudiere: null,
    NombreContratChaudiere: null,
    mntredevContratChaudiere: null,
    NumSousTraitChaudiere: null,
    TarifSousTraitChaudiere: null,
    numerocontratdesenfumage: null,
    datedesenfumage: null,
    nombrevisitedesenfumage: null,
    montantredevancedesenfumage: null,
    NumSousTraitDesenfum: null,
    TarifSousTraitDesenfum: null,
  },
  site_horaires: {
    cptsit: 1,
    hor_lun_ouv: '09:00', hor_lun_fer: '19:00',
    hor_mar_ouv: '09:00', hor_mar_fer: '19:00',
    hor_mer_ouv: '09:00', hor_mer_fer: '19:00',
    hor_jeu_ouv: '09:00', hor_jeu_fer: '19:00',
    hor_ven_ouv: '09:00', hor_ven_fer: '19:00',
    hor_sam_ouv: '09:00', hor_sam_fer: '19:00',
    hor_dim_ouv: '00:00', hor_dim_fer: '00:00',
  },
  site_registre_securite: { numero: 1, cptsit: 1, date_maj: new Date(Date.UTC(2024, 0, 1)) },
  site_materiels: {
    NumeroSiteMateriel: 1,
    NumeroSite: 1,
    RepereSurSite: 1,
    Repere: 'CL1',
    Emplacement: 'Toiture',
    Quantite: 1,
    Marque: 'Daikin',
    Type: 'Split',
    Reference: 'REF-1',
    NumeroSerie: 'SN1',
    Reversible: 'OUI',
    ResistanceElectrique: 'NON',
    PuissanceFrigo: 5.5,
    PuissanceCalo: 6,
    FluideQuantite: 'R32',
    DateMiseEnService: '01/01/2015',
    TypeTelecommande: 'Filaire',
    NbreTelecommande: 1,
    EmplacementTelecommande: 'Bureau',
    Disjoncteurs: null,
    DisjoncteurPrincipal: null,
    DisjoncteurArmoirePrincipale: null,
    DisjoncteurCoffretIndependant: null,
    AccessibiliteGroupe: null,
    AccessibiliteCassettes: null,
    SupportGroupes: null,
    EtatSupports: null,
    NbreFiltreRoofTop: null,
    ReferenceFiltreRoofTop: null,
    NbreCourroiesRoofTop: null,
    ReferenceCourroiesRoofTop: null,
    AppointChauffageSurRoof: null,
    NbreAerotherme: null,
    AerothermeGazElec: null,
    RideauAir: 0,
    NbreRideauType: null,
    PuissanceRideau: null,
    TypeDisjoncteurRideau: null,
    SasEntree: 0,
    ClimLocauxSociauxEmplacement: null,
    ClimLocauxSociauxEmplacementGroupeExterieur: null,
    ClimLocauxSociauxMarque: null,
    ClimLocauxSociauxType: null,
    ClimLocauxSociauxReference: null,
    ClimLocauxSociauxNumeroSerie: null,
    ClimLocauxSociauxDateMiseService: null,
    ClimLocauxSociauxReversible: 0,
    ClimLocauxSociauxFluideQuantite: null,
    Radiateurs: 0,
    NbreRadiateurs: 2.5,
    LocalisationRadiateurs: null,
    DisjoncteurRadiateursTypeIntensite: null,
    VMC: 0,
    LocalisationVMC: null,
    Photos: 0,
    RapportsMaintenance: null,
    DevisEnCours: null,
    DevisValide: null,
    ControleEtancheite: null,
    Observations: null,
    DateCE: new Date(Date.UTC(2024, 0, 1)),
    CE_Edite: 1,
    DateAchat: new Date(Date.UTC(2015, 0, 1)),
  },
  interventions: {
    numintint: 1,
    numint: 1,
    cptsit: 1,
    codint: 'FMC',
    typint: '1',
    staint: 9,
    natureintervention: 1,
    datheuapp: new Date(Date.UTC(2025, 0, 1)),
    datheulim: new Date(Date.UTC(2025, 0, 8)),
    datintpre: new Date(Date.UTC(2025, 0, 2)),
    heuintpre: new Date(Date.UTC(1899, 11, 30, 9, 0, 0)),
    datint: new Date(Date.UTC(2025, 0, 2)),
    heuarrint: new Date(Date.UTC(1899, 11, 30, 9, 30, 0)),
    heudepint: new Date(Date.UTC(1899, 11, 30, 11, 0, 0)),
    tpsallint: new Date(Date.UTC(1899, 11, 30, 0, 30, 0)),
    tpsretint: new Date(Date.UTC(1899, 11, 30, 0, 30, 0)),
    datefintech: null,
    objint: 'Entretien annuel',
    comint: null,
    dirint: null,
    comintposint: null,
    comtec: 'RAS',
    refint: 'REF1',
    refcliint: 'DI1',
    cheficdemcli: null,
    cheficdemint: '/bons/1.pdf',
    CheminDossEtanch: null,
    codcon: 'C1',
    codpan: 1,
    pannoncli: 0,
    traitepar: 1,
    saisiepar: 1,
    prediagpar: null,
    prediagres: 0,
    envoisoustraitantpar: null,
    numerodemandesoustraitant: null,
    numutipre: 1,
    nbrtecint: 1,
    retourficheoriginal: 1,
    retourfichecopie: 0,
    retourfichecopieordi: 0,
    majregsec: 1,
    controleetancheite: 1,
    controleetancheiteponctuel: 0,
    photofaite: 1,
    auditfait: 0,
    heuvis: 0,
    visitegratuite: 0,
    devisafaire: 0,
    devisfait: 0,
    devisanepasfaire: 0,
    comdevis: null,
    comdevisinterne: null,
    numdevacc: null,
    numdev: null,
    duplicatafait: 0,
    intfac: 0,
    intfactok: 1,
    mntfac: 250.5,
    mntfmc: 250.5,
    mntst: 0,
    rappel24h: 0,
    rappel48h: 0,
    rappel72h: 0,
    rappelsemaine: 0,
    dateenvoimail: null,
    sigsitimg: null,
    sigcliimg: null,
    sigtecimg: null,
    sigsit2: null,
    sigcli2: null,
    sigtec2: null,
    sigtecjson: '{"points":[1,2,3]}',
    sigclijson: 'not-json',
    sigsitbase64: null,
    creele: new Date(Date.UTC(2025, 0, 1)),
    majle: new Date(Date.UTC(2025, 0, 3)),
    nbrappint: 4,
    imprimeepar: 1,
    retourficheinterventionpar: null,
    devisepar: null,
    stadev: null,
    numpartenaire: null,
    numdevpartenaire: null,
    mnthtdevis: null,
    nummodres: 6,
    nbrpagfax: 1.5,
    intafact: 0,
    numerocommande: null,
    sigsit: 'Prestations réalisées',
    sigtec: null,
    sigcli: null,
    commajregsec: null,
    datesignaturecontrat: null,
    mnthtdevpartenaire: null,
    numerocontratclient: null,
  },
  site_materiels_intervention: { NumeroSiteMateriel: 1, NumeroInter: 1 },
  intervention_techniciens: { numintuti: 1, numintint: 1, numuti: 1 },
  fiches_intervention: {
    numFicheInt: 1,
    numIntInt: 1,
    numBon: 1,
    dateFicheInt: new Date(Date.UTC(2025, 0, 2)),
    heureDebut: new Date(Date.UTC(1899, 11, 30, 9, 0, 0)),
    heureFin: new Date(Date.UTC(1899, 11, 30, 11, 0, 0)),
    tempsAller: 0.5,
    tempsRetour: 0.5,
    remarques: null,
  },
  heures_techniciens: {
    Numero: 1,
    NumeroTech: 1,
    TypeInterv: 1,
    NumInterv: 1,
    NomInterv: 'Entretien',
    DateInterv: new Date(Date.UTC(2025, 0, 2)),
    HeureDebut: new Date(Date.UTC(1899, 11, 30, 9, 0, 0)),
    HeureFin: new Date(Date.UTC(1899, 11, 30, 11, 0, 0)),
    HeureDebut_FMC: null,
    HeureFin_FMC: null,
    InterdictionModif: 0,
    NumeroSite: 1,
    DateSaisie: new Date(Date.UTC(2025, 0, 2)),
    NePasComptabiliser: 0,
  },
  devis: {
    NumeroDevis: 1,
    NumeroDevisInterne: 'D1',
    StatutDevis: 6,
    NomFichierDevis: 'devis1.pdf',
    NomFichierDevisPartenaire: null,
    NumeroInterventionInterne: 1,
    NumeroSite: 1,
    CommentaireClientDevis: null,
    NumeroClient: 1,
    MontantFournitureDevis: 100,
    MainOeuvreDevis: 2,
    NbreDeplacementDevis: 1,
    DateEnvoiDevis: new Date(Date.UTC(2025, 0, 1)),
    EnvoyePar: 1,
    NumeroPartenaire: null,
    NumeroDevisPartenaire: null,
    MontantHTDevis: 200,
    MontantHTDevisPartenaire: null,
    NumeroCommande: null,
    DateDevis: new Date(Date.UTC(2025, 0, 1)),
    TypePanneDevis: null,
    QteMaterielDevis: null,
    coutheuremainoeuvre: 45.5,
    coutdeplacement: 20,
    NumeroDevisRemplacement: null,
  },
  planifications: {
    numeroplanification: 1,
    numcli: 1,
    T1: new Date(Date.UTC(2025, 2, 1)),
    T2: null, T3: null, T4: new Date(Date.UTC(2025, 8, 1)),
    T5: null, T6: null, T7: null, T8: null, T9: null, T10: null, T11: null, T12: null,
    nombrevisite: 2,
    recurrent: 1,
    datefinrecurrence: null,
  },
  vehicules: {
    NumVehicule: 1,
    EtatVehicule: 0,
    Dernier_KM: 15000,
    Immatriculation: 'AB-123-CD',
    DateMiseCirculation: new Date(Date.UTC(2020, 0, 1)),
    KM_a_l_achat: 0,
    Km_Inter_Revision: 20000,
    Temps_Mois_Inter_Revision: 12,
    Champ_Libre: null,
    Garantie: 1,
    Nb_KM_Garantie: 100000,
    Temps_Mois_Garantie: 36,
    Leasing: 0,
    Nb_Km_Leasing: null,
    Temps_Mois_Leasing: null,
    Date_Fin_Leasing: null,
    Conducteur: 1,
    NumTelepeage: null,
    CodeCarteEssence: null,
    NumCarteEssence: null,
    Marque: 'Renault',
    Modele: 'Kangoo',
    Societe: 0,
    CritAir: 1,
  },
  vehicule_evenements: {
    NumEV: 1,
    DateEv: new Date(Date.UTC(2025, 0, 1)),
    Km: 16000,
    Conducteur: 1,
    Immat: 'AB-123-CD',
    TypeEv: 1,
  },
};
