import { trim, toBoolNotNull, toNumberOrNull, toIntOrNull } from '../lib/transform.mjs';

export default {
  target: 'intervenants',
  conflictColumns: ['legacy_id'],
  source: `
    select numintervenant, codint, nomint, adrint, codposint, vilint, telint, faxint, adrmelint,
           NomDirigeant_Interv, TelDirigeant_Interv, Mail_Dirigeant_Interv,
           NomInterlocuteur_Interv, TelInterlocuteur_Interv, Info_Interv, Histo_FMC_Interv,
           VillesInterventions_Interv, Latitude_Interv, Longitude_Interv, PrecisionGeo_Interv,
           Provenance_Interv, IndMaint_Interv, Ind_Depann_Interv, Ind_Travaux_Interv, Ind_React_Interv,
           DossierOrdi_Interv, TexteNeplusInterv, EstTech, NePlusIntervenir, Status_Prospect,
           Status_ST_FMC, Status_ST_FMC_Ponctuel, Status_Act_Poss_Maint, Status_Act_Poss_Depan,
           Status_Act_Poss_Travaux, Status_Act_Donn_Maint, Status_Act_Donn_Depan, Status_Act_Donn_Travaux,
           Zone_Nationale, MailFacturation, SiteInternet, ExistePlus, AutoLiquidation
    from Intervenant
  `,
  transform(row) {
    return {
      legacy_id: row.numintervenant,
      code: trim(row.codint) ?? `INTERVENANT_${row.numintervenant}`,
      nom: trim(row.nomint),
      adresse: trim(row.adrint),
      code_postal: trim(row.codposint),
      ville: trim(row.vilint),
      telephone: trim(row.telint),
      fax: trim(row.faxint),
      email: trim(row.adrmelint),
      dirigeant_nom: trim(row.NomDirigeant_Interv),
      dirigeant_telephone: trim(row.TelDirigeant_Interv),
      dirigeant_email: trim(row.Mail_Dirigeant_Interv),
      interlocuteur_nom: trim(row.NomInterlocuteur_Interv),
      interlocuteur_telephone: trim(row.TelInterlocuteur_Interv),
      informations: trim(row.Info_Interv),
      historique_fmc: trim(row.Histo_FMC_Interv),
      villes_codes_postaux: trim(row.VillesInterventions_Interv),
      latitude: toNumberOrNull(row.Latitude_Interv),
      longitude: toNumberOrNull(row.Longitude_Interv),
      precision_geo: trim(row.PrecisionGeo_Interv),
      provenance: trim(row.Provenance_Interv),
      // interlocuteur_fmc_id / cree_par_id : posés par le second passage
      // (mapping/intervenants_fk_utilisateurs.mjs), une fois `utilisateurs` chargée.
      interlocuteur_fmc_id: null,
      cree_par_id: null,
      note_maintenance: toIntOrNull(row.IndMaint_Interv),
      note_depannage: toIntOrNull(row.Ind_Depann_Interv),
      note_travaux: toIntOrNull(row.Ind_Travaux_Interv),
      note_reactivite: toIntOrNull(row.Ind_React_Interv),
      dossier_chemin: trim(row.DossierOrdi_Interv),
      motif_ne_plus_intervenir: trim(row.TexteNeplusInterv),
      est_technicien_interne: toBoolNotNull(row.EstTech, false),
      ne_plus_intervenir: toBoolNotNull(row.NePlusIntervenir, false),
      est_prospect: toBoolNotNull(row.Status_Prospect, false),
      est_sous_traitant: toBoolNotNull(row.Status_ST_FMC, false),
      est_sous_traitant_ponctuel: toBoolNotNull(row.Status_ST_FMC_Ponctuel, false),
      peut_maintenance: toBoolNotNull(row.Status_Act_Poss_Maint, false),
      peut_depannage: toBoolNotNull(row.Status_Act_Poss_Depan, false),
      peut_travaux: toBoolNotNull(row.Status_Act_Poss_Travaux, false),
      confie_maintenance: toBoolNotNull(row.Status_Act_Donn_Maint, false),
      confie_depannage: toBoolNotNull(row.Status_Act_Donn_Depan, false),
      confie_travaux: toBoolNotNull(row.Status_Act_Donn_Travaux, false),
      zone_nationale: toBoolNotNull(row.Zone_Nationale, false),
      email_facturation: trim(row.MailFacturation),
      site_internet: trim(row.SiteInternet),
      n_existe_plus: toBoolNotNull(row.ExistePlus, false),
      autoliquidation: toBoolNotNull(row.AutoLiquidation, false),
    };
  },
};
