import { trim, toBoolNotNull, toIntOrNull, toNumberOrNull } from '../lib/transform.mjs';
import { parseLooseDateText, mssqlDateOnly } from '../lib/dates.mjs';

export default {
  target: 'site_materiels',
  conflictColumns: ['legacy_id'],
  lookups: [
    { name: 'siteIdByLegacyId', table: 'sites', column: 'legacy_id' },
    { name: 'fluideIdByLibelle', table: 'types_fluide', column: 'libelle' },
  ],
  source: `
    select NumeroSiteMateriel, NumeroSite, RepereSurSite, Repere, Emplacement, Quantite, Marque,
           [Type], Reference, NumeroSerie, Reversible, ResistanceElectrique, PuissanceFrigo,
           PuissanceCalo, FluideQuantite, DateMiseEnService, TypeTelecommande, NbreTelecommande,
           EmplacementTelecommande, Disjoncteurs, DisjoncteurPrincipal, DisjoncteurArmoirePrincipale,
           DisjoncteurCoffretIndependant, AccessibiliteGroupe, AccessibiliteCassettes, SupportGroupes,
           EtatSupports, NbreFiltreRoofTop, ReferenceFiltreRoofTop, NbreCourroiesRoofTop,
           ReferenceCourroiesRoofTop, AppointChauffageSurRoof, NbreAerotherme, AerothermeGazElec,
           RideauAir, NbreRideauType, PuissanceRideau, TypeDisjoncteurRideau, SasEntree,
           ClimLocauxSociauxEmplacement, ClimLocauxSociauxEmplacementGroupeExterieur,
           ClimLocauxSociauxMarque, ClimLocauxSociauxType, ClimLocauxSociauxReference,
           ClimLocauxSociauxNumeroSerie, ClimLocauxSociauxDateMiseService,
           ClimLocauxSociauxReversible, ClimLocauxSociauxFluideQuantite, Radiateurs,
           NbreRadiateurs, LocalisationRadiateurs, DisjoncteurRadiateursTypeIntensite, VMC,
           LocalisationVMC, Photos, RapportsMaintenance, DevisEnCours, DevisValide,
           ControleEtancheite, Observations, DateCE, CE_Edite, DateAchat
    from SiteMateriel
  `,
  transform(row, ctx) {
    const siteId = ctx.get('siteIdByLegacyId').get(row.NumeroSite) ?? null;
    const fluideLibelle = trim(row.FluideQuantite);
    const dateMES = parseLooseDateText(row.DateMiseEnService);

    return {
      legacy_id: row.NumeroSiteMateriel,
      site_id: siteId,
      repere_sur_site: toIntOrNull(row.RepereSurSite),
      repere: trim(row.Repere),
      emplacement: trim(row.Emplacement),
      quantite: toIntOrNull(row.Quantite),
      marque: trim(row.Marque),
      type_equipement: trim(row.Type),
      reference: trim(row.Reference),
      numero_serie: trim(row.NumeroSerie),
      reversible: trim(row.Reversible),
      resistance_electrique: trim(row.ResistanceElectrique),
      puissance_frigo_w: toNumberOrNull(row.PuissanceFrigo),
      puissance_calo_w: toNumberOrNull(row.PuissanceCalo),
      fluide_libelle: fluideLibelle,
      fluide_id: fluideLibelle ? ctx.get('fluideIdByLibelle').get(fluideLibelle) ?? null : null,
      charge_fluide_kg: toNumberOrNull(row.NbreRadiateurs),
      date_mise_en_service_brut: dateMES.brut,
      date_mise_en_service: dateMES.date,
      type_telecommande: trim(row.TypeTelecommande),
      nombre_telecommandes: toIntOrNull(row.NbreTelecommande),
      emplacement_telecommande: trim(row.EmplacementTelecommande),
      disjoncteur_general: trim(row.Disjoncteurs),
      disjoncteur_principal: trim(row.DisjoncteurPrincipal),
      disjoncteur_armoire_principale: trim(row.DisjoncteurArmoirePrincipale),
      disjoncteur_coffret_independant: trim(row.DisjoncteurCoffretIndependant),
      accessibilite_groupe: trim(row.AccessibiliteGroupe),
      accessibilite_cassettes: trim(row.AccessibiliteCassettes),
      support_groupes: trim(row.SupportGroupes),
      etat_supports: toIntOrNull(row.EtatSupports),
      rooftop_nombre_filtres: toIntOrNull(row.NbreFiltreRoofTop),
      rooftop_reference_filtres: trim(row.ReferenceFiltreRoofTop),
      rooftop_nombre_courroies: toIntOrNull(row.NbreCourroiesRoofTop),
      rooftop_reference_courroies: trim(row.ReferenceCourroiesRoofTop),
      rooftop_appoint_chauffage: trim(row.AppointChauffageSurRoof),
      aerotherme_nombre: trim(row.NbreAerotherme),
      aerotherme_gaz_elec: trim(row.AerothermeGazElec),
      rideau_air: toBoolNotNull(row.RideauAir, false),
      rideau_air_nombre_type: trim(row.NbreRideauType),
      rideau_air_puissance: trim(row.PuissanceRideau),
      rideau_air_disjoncteur: trim(row.TypeDisjoncteurRideau),
      sas_entree: toBoolNotNull(row.SasEntree, false),
      clim_locaux_sociaux_emplacement: trim(row.ClimLocauxSociauxEmplacement),
      clim_locaux_sociaux_emplacement_groupe_exterieur: trim(row.ClimLocauxSociauxEmplacementGroupeExterieur),
      clim_locaux_sociaux_marque: trim(row.ClimLocauxSociauxMarque),
      clim_locaux_sociaux_type: trim(row.ClimLocauxSociauxType),
      clim_locaux_sociaux_reference: trim(row.ClimLocauxSociauxReference),
      clim_locaux_sociaux_numero_serie: trim(row.ClimLocauxSociauxNumeroSerie),
      clim_locaux_sociaux_date_mise_service: trim(row.ClimLocauxSociauxDateMiseService),
      clim_locaux_sociaux_reversible: toBoolNotNull(row.ClimLocauxSociauxReversible, false),
      clim_locaux_sociaux_fluide_quantite: trim(row.ClimLocauxSociauxFluideQuantite),
      radiateurs: toBoolNotNull(row.Radiateurs, false),
      radiateurs_localisation: trim(row.LocalisationRadiateurs),
      radiateurs_disjoncteur: trim(row.DisjoncteurRadiateursTypeIntensite),
      vmc: toBoolNotNull(row.VMC, false),
      vmc_localisation: trim(row.LocalisationVMC),
      photos: toBoolNotNull(row.Photos, false),
      rapports_maintenance: trim(row.RapportsMaintenance),
      devis_en_cours: trim(row.DevisEnCours),
      devis_valide: trim(row.DevisValide),
      controle_etancheite_libelle: trim(row.ControleEtancheite),
      observations: trim(row.Observations),
      date_controle_etancheite: mssqlDateOnly(row.DateCE),
      certificat_etancheite_edite: toBoolNotNull(row.CE_Edite, false),
      intervention_id: null, // posé par le second passage (mapping/site_materiels_intervention.mjs)
      date_achat: mssqlDateOnly(row.DateAchat),
    };
  },
};
