-- Chargement des référentiels depuis legacy/referentiels.txt (voir docs/plan/etape-1.md).
-- Idempotent : "on conflict do nothing" partout.

-- StatusInterv (10 codes officiels) + 4 codes historiques disparus du référentiel source.
insert into public.statuts_intervention (code, libelle, ordre_affichage, actif) values
  (-1, 'Materiel à commander', 1, true),
  (2, 'Attente Materiel', 2, true),
  (1, 'A Planifier', 3, true),
  (7, 'Cloturé', 4, true),
  (8, 'Annulé avec accord client', 5, true),
  (20, 'Annulé en interne', 6, true),
  (9, 'Réalisé - A Valider', 7, true),
  (10, 'Résolu par téléphone', 8, true),
  (17, 'Ne pas Intervenir', 9, true),
  (19, 'Attente Fiche', 10, true),
  (3, 'Attente de matériel', 0, false),
  (4, 'En cours', 0, false),
  (5, 'En cours chez le sous-traitant', 0, false),
  (6, 'Effectuée en attente retour fiche', 0, false)
on conflict (code) do nothing;

-- TypeInterv, code 0 "Toutes" non chargé.
insert into public.types_intervention (code, libelle, ordre_affichage) values
  (14, 'Appel', 0),
  (1, 'Entretien', 2),
  (13, 'Maint.Chaudiere', 2),
  (2, 'Depannage', 3),
  (3, 'Devis SAV', 4),
  (12, 'Devis SAV (TR)', 5),
  (5, 'En travaux', 6),
  (7, 'Désenfumage', 7),
  (9, 'Audit', 8),
  (4, 'Autre', 9),
  (6, 'En Création', 10),
  (8, 'Inter.réalisée en attente devis signé client', 11)
on conflict (code) do nothing;

-- StatutFacture.
insert into public.statuts_facturation (code, libelle, ordre_affichage) values
  (1, 'A facturer', 1),
  (2, 'A définir', 2),
  (8, 'A definir (Par Fabien)', 3),
  (3, 'Non Facturable', 4),
  (7, 'Non Facturable (SG)', 4),
  (4, 'Facturé', 5),
  (6, 'Attendre 100% fini', 6),
  (5, 'Facturé (au trimestre)', 7),
  (9, 'Stand by', 8),
  (10, 'En Attente de Commande', 9),
  (11, 'SIRET Non renseigné', 10)
on conflict (code) do nothing;

-- SousType (= nature technique).
insert into public.sous_types_intervention (code, libelle) values
  (1, 'Climatisation'),
  (2, 'Ventilation'),
  (3, 'Refrigeration'),
  (4, 'Plomberie'),
  (5, 'Chauffage'),
  (6, 'Groupe eau glacée'),
  (7, 'Gaz'),
  (8, 'Roof top'),
  (9, 'Electricité'),
  (11, 'FEVI (Extraction)')
on conflict (code) do nothing;

-- ModeResolution (historique).
insert into public.modes_resolution (code, libelle) values
  (1, 'par téléphone'),
  (2, 'en même temps que la visite d''entretien'),
  (3, 'par fax'),
  (4, 'intervention physique')
on conflict (code) do nothing;

-- Activites (20 métiers).
insert into public.activites (code, libelle) values
  (1, 'Climatisation'),
  (2, 'Chauffage'),
  (3, 'Ramonage'),
  (4, 'Plomberie'),
  (5, 'Petite Plomberie'),
  (6, 'Froid (Ex: Ch. Froide)'),
  (7, 'Desenfumage'),
  (8, 'Gaineur'),
  (9, 'Nettoyage/Desinfection'),
  (10, 'Electricité'),
  (11, 'Zingueur'),
  (12, 'Ventilation'),
  (13, 'Assainissement'),
  (14, 'Detection GAZ / Incendie'),
  (15, 'Etude Structure'),
  (16, 'Calorifuges/Isolation'),
  (17, 'Vidange/pompage'),
  (18, 'Etancheité/Couverture/Zinguerie'),
  (19, 'Traitement de l''eau'),
  (20, 'Etancheur')
on conflict (code) do nothing;

-- ZoneGeographique.
insert into public.zones_geographiques (code, libelle) values
  (63, 'Bruno.Zone Sud Est'),
  (68, 'Bx.Zone Bayonne'),
  (69, 'Bx.Zone Pau'),
  (70, 'Bx.Zone Bordeaux'),
  (71, 'F. Nantes'),
  (72, 'Bx.Zone Limoges'),
  (74, 'Bx.Zone Agen'),
  (75, 'L. La Rochelle'),
  (76, 'F. Centre'),
  (77, 'F. Bretagne Nord'),
  (78, 'Bruno.Zone Perpignan'),
  (79, 'F. Normandie Ouest'),
  (80, 'F. Angers/Le Mans/Tours'),
  (82, '00. Hors Contrat'),
  (84, 'F. Bretagne Sud'),
  (85, 'L. Poitiers/Niort/La Roche sur Yon'),
  (86, 'L. Angouleme'),
  (87, 'Bx.Zone Bergerac'),
  (89, '00. Hors Contrat (Kingfisher)'),
  (91, '0. Zone Nord Nord (Générale)'),
  (92, 'ZZ.Libre 3'),
  (93, 'Bx.Zone Brive la Gaillarde'),
  (94, 'F. Normandie Est'),
  (96, 'Bx.Zone Perigueux'),
  (97, 'F. Paris'),
  (99, 'ZZ.Libre 2'),
  (100, 'Bx.Ancien Zone FC 17 (OGF)'),
  (101, '0. Zone Auvergne (Générale)'),
  (106, 'ZZ.Libre.12'),
  (107, 'ZZ.Libre.11'),
  (108, 'F. OGF (CP 85)'),
  (111, 'ZZ.Libre 5'),
  (112, 'Bx.Zone Toulouse'),
  (114, '0. Zone Lyon (Générale)'),
  (115, '0. Zone Paris (Générale)'),
  (116, 'ZZ.Libre 4'),
  (117, 'ZZ.Libre 9'),
  (118, 'ZZ.Libre 7'),
  (119, 'ZZ.Libre 1'),
  (120, 'ZZ.Libre.10'),
  (121, 'ZZ.Libre 6'),
  (122, 'ZZ.Libre 8'),
  (123, 'Benoit. Zone Nord Est')
on conflict (code) do nothing;

-- Societe. est_fmc = true pour les codes 1, 111, 112, 113 (cf. brief étape 1).
insert into public.societes (code, libelle, est_fmc) values
  (1, 'Ancien Salarié FMC', true),
  (2, 'ACF', false),
  (3, 'Broceliande', false),
  (4, 'Equipage', false),
  (5, 'Guerit', false),
  (6, 'HPAC', false),
  (7, 'LGC Climatisation', false),
  (8, 'Mansuy', false),
  (9, 'MISO', false),
  (10, 'PPI', false),
  (11, 'R-CLIM', false),
  (12, 'SEE Sautereau', false),
  (13, 'Solution Chauffage', false),
  (14, 'LGC Climatisation', false),
  (15, '1A', false),
  (16, 'Nord Climatisation', false),
  (17, 'FCT', false),
  (18, 'Aquaplanet', false),
  (19, 'France Install', false),
  (20, 'Chauffage Landividisiau', false),
  (21, 'SFM Batiment', false),
  (22, 'Loire Froid Climatisation', false),
  (23, 'FC 17', false),
  (24, 'FC Auvergne', false),
  (25, 'CVC Froid', false),
  (26, 'ECO2 CVC', false),
  (27, 'SARL LEURS', false),
  (28, 'SARL Frederic Lafon', false),
  (29, 'Castillon Chauffage', false),
  (30, 'SOOFLE', false),
  (31, 'FMC (OGF Audit)', false),
  (32, 'EMD', false),
  (33, 'GAZ TECHNIQUE', false),
  (34, 'TREILLARD ETS', false),
  (35, 'Maillet ETS', false),
  (36, 'SAS MAGADOUX DEMARTY', false),
  (37, 'EURL CCB Remi Borde', false),
  (38, 'FERLUC', false),
  (39, 'ATCS', false),
  (40, 'BOULLARD ETS', false),
  (41, 'ABBYS VIDANGE CORREZE', false),
  (42, 'SI2G', false),
  (43, 'SARL POMPES DENIS', false),
  (44, 'FCCF', false),
  (45, 'EURL SODECIS', false),
  (46, 'GTC', false),
  (47, 'SANICENTRE', false),
  (48, 'A.AIR.CLIM', false),
  (49, 'SAS 2R', false),
  (50, 'Tekniclima', false),
  (51, 'A DEFINIR', false),
  (52, 'AMBIANCE CLIMATISATION', false),
  (53, 'CFC34', false),
  (54, 'DELTA T', false),
  (55, 'EDDIA', false),
  (56, 'DE2C', false),
  (57, 'GENESTE CHAUFFAGE', false),
  (58, 'BENEO', false),
  (59, 'INVERT''AIR CLIMATISATION', false),
  (60, 'AVIPUR', false),
  (61, 'AMARI BRANDAO', false),
  (62, 'Chaudiere', false),
  (63, 'A.R.I.E.B', false),
  (64, 'Visite', false),
  (65, 'SAS CHAPELAT ANDRÉ', false),
  (67, 'ACP', false),
  (68, 'TWINS ENERGIE', false),
  (69, 'EURL ACP', false),
  (70, 'DARCHIS SARACHMAN', false),
  (71, 'AUVERCLIM', false),
  (72, 'SGA MEYER', false),
  (73, 'Espace Chauffage', false),
  (74, 'GTI', false),
  (75, '2M2D', false),
  (76, 'Planete Froid', false),
  (77, 'MAYANS ENERGIES', false),
  (78, 'DARTHOU', false),
  (79, 'MB Multi', false),
  (80, 'EMDBEILLARD', false),
  (81, 'AUVERGNE PRO CLIM', false),
  (82, 'SAS ACGLS', false),
  (83, 'JSENERGIE', false),
  (84, 'THERMI SERVICE', false),
  (85, 'ARITH CHAUFFAGE', false),
  (86, 'SARL DEMOUGE', false),
  (87, 'E2S', false),
  (88, 'EUROENERGIE', false),
  (89, 'SPEED PLOMBERIE', false),
  (90, 'FATALOT', false),
  (91, 'INDO', false),
  (92, 'COTE NOUVELLES ENERGIES', false),
  (93, 'BINET ENERGIES', false),
  (94, 'ETS SERVAIS', false),
  (95, 'THERMI CHAUFF', false),
  (96, 'GB Services', false),
  (97, 'BESOINS SERVICES 24', false),
  (98, 'LC 74 PLOMBIER CHAUFFAGISTE', false),
  (99, 'Atelier Thermique Corriou (ATC)', false),
  (100, 'SAS RAYNAUD', false),
  (101, 'A Air Clim', false),
  (102, 'SIMIE', false),
  (103, 'CLIMCHAUD ENERGIES', false),
  (104, 'CAPET THERMIE', false),
  (105, 'ETS BRIFFAUT', false),
  (106, 'LCO', false),
  (107, 'FCT 13', false),
  (108, 'SAS LEITAO', false),
  (109, 'JENERGIE', false),
  (110, 'FPCLIM', false),
  (111, 'Z- FMC Clim (Ne pas effacer)', true),
  (112, 'Z- FMC Maintenance (Ne pas effacer)', true),
  (113, 'Z- FMC Bureau (Ne pas effacer)', true),
  (114, 'CR climatisation', false),
  (115, 'AD CHAUFFAGE SERVICES', false),
  (116, 'A2L CLIM', false),
  (117, 'EURL BOUCHER', false),
  (118, 'CUENOD', false),
  (119, 'JHC GAZ', false),
  (120, 'Sté NORMAND', false),
  (121, 'IN&TECH', false),
  (122, 'REVOLUTION''AIR', false),
  (123, 'SN BRUNORI', false),
  (124, 'DMC', false),
  (125, 'KAYRO', false)
on conflict (code) do nothing;

-- VisitesMaint : id = Nombre_Visites, lib = Commentaire, o = Ecart_Permis_Jour (cf. commentaire de la table).
insert into public.ecarts_visites (nombre_visites, ecart_jours, commentaire) values
  (2, 1, 'Ecart mini 10 mois'),
  (4, 2, 'Ecart mini 4,5 mois'),
  (5, 3, 'Ecart Mini 2 mois'),
  (6, 4, 'Ecart mini 1,5 mois'),
  (7, 6, 'Ecart mini 25 jours'),
  (9, 12, 'Ecart mini 15 jours')
on conflict (nombre_visites) do nothing;

-- Liste_Type_Gaz : valeurs fixes, codes internes (voir commentaire de la table).
insert into public.familles_gaz (code, libelle) values
  (1, 'HCFC'),
  (2, 'HFC'),
  (3, 'HFO')
on conflict (code) do nothing;

-- TypeFluide. famille_gaz_id déduit de la chimie connue du fluide (à vérifier à l'étape 2).
insert into public.types_fluide (code, libelle, gwp, famille_gaz_id) values
  (28, 'A confirmer', null, null),
  (29, 'Plusieurs (Voir Audit)', null, null),
  (30, 'R290', 3, null),
  (33, 'R513A', 631, (select id from public.familles_gaz where code = 3)),
  (21, 'R32', 675, (select id from public.familles_gaz where code = 2)),
  (25, 'R448a', 1397, (select id from public.familles_gaz where code = 3)),
  (26, 'R449a', 1397, (select id from public.familles_gaz where code = 3)),
  (24, 'R134a', 1430, (select id from public.familles_gaz where code = 2)),
  (4, 'R407C', 1774, (select id from public.familles_gaz where code = 2)),
  (6, 'R22', 1810, (select id from public.familles_gaz where code = 1)),
  (5, 'R410a', 2088, (select id from public.familles_gaz where code = 2)),
  (32, 'R452a', 2140, (select id from public.familles_gaz where code = 2)),
  (27, 'R404a', 3922, (select id from public.familles_gaz where code = 2))
on conflict (code) do nothing;

-- TypeAudit (renommée types_equipement). famille = chiffre avant le premier "-" du libellé.
insert into public.types_equipement (code, libelle, famille)
select code, libelle, nullif(trim(split_part(libelle, '-', 1)), '')::smallint
from (values
  (1, '1- A definir (Divers)'),
  (2, '1- Boitier BS'),
  (3, '1- Telecommande'),
  (4, '1- Telec Centralisée'),
  (5, '1- Plenum Airzone'),
  (6, '1- Tel. Airzone'),
  (7, '1- Acc. Airzone'),
  (8, '1- Web Serveur Airzone'),
  (9, '1- Purificateur'),
  (10, '1- Monosplit'),
  (11, '1- Multisplit'),
  (12, '1- Twin'),
  (13, '1- VRV'),
  (14, '1- VRV à eau'),
  (15, '1- Cave à vin'),
  (16, '1- Window'),
  (17, '1- Gr. à eau perdue'),
  (18, '1- Monobloc'),
  (19, '1- Mural'),
  (20, '1- Console'),
  (21, '1- Gainable'),
  (22, '1- Cassette'),
  (23, '1- Plafonnier'),
  (24, '1- Armoire'),
  (25, '1- Clim mobile'),
  (26, '1- Bouches/Grilles'),
  (27, '1- Roof (A définir)'),
  (28, '1- Roof Thermo'),
  (29, '1- Roof Gaz'),
  (30, '1- Roof Thermo + Gaz'),
  (31, '1- Roof F.Seul + Gaz'),
  (32, '1- Gr. Eau glacée'),
  (33, '1- V. Convecteur'),
  (34, '1- Deshu'),
  (35, '0- NC'),
  (36, '2- A definir (Divers)'),
  (37, '2- Chaudiere (A definir)'),
  (38, '2- Chaudiere Gaz'),
  (39, '2- Chaudiere Fioul'),
  (40, '2- GE PAC Air/Eau'),
  (41, '2- PAC Piscine'),
  (42, '2- PAC Boucle d''eau'),
  (43, '2- UI PAC Air/Eau'),
  (44, '2- Ballon Thermo'),
  (45, '2- Thermostat'),
  (46, '2- RAC (A definir)'),
  (47, '2- RAC electrique'),
  (48, '2- RAC  Elec Encastré'),
  (49, '2- RAC  Elec Apparent'),
  (50, '2- RAC Thermo'),
  (51, '2- RAC Thermo Encastré'),
  (52, '2- RAC Thermo Apparent'),
  (53, '2- RAC sans chauffage'),
  (54, '2- RAC à eau'),
  (55, '2- Rad. Elec'),
  (56, '2- Rad à eau'),
  (57, '2- Aerotherme (A definir)'),
  (58, '2- Aérotherme Gaz'),
  (59, '2- Aérotherme Elec'),
  (60, '2- Aérotherme Eau'),
  (61, '3- A definir (Divers)'),
  (62, '3- Extracteur Labo'),
  (63, '3- Ventilation Salon'),
  (64, '3- Detection presence'),
  (65, '3- Voyants V/R'),
  (66, '3- Caisson Filtrant'),
  (67, '3- Filtre Media'),
  (68, '3- Filtre charbon'),
  (69, '3- Media+Charbon'),
  (70, '3- Bouches'),
  (71, '4- A definir (Divers)'),
  (72, '4- Specifique/Divers'),
  (73, '4- Simple Flux'),
  (74, '4- Double Flux'),
  (75, '4- Extracteur Cuisine'),
  (76, '4- Grille (Souff/Extraction)'),
  (77, '4- Hotte'),
  (78, '4- CTA'),
  (79, '5- A definir (Divers)'),
  (80, '5- Chauffe Eau'),
  (81, '5- Styx'),
  (82, '6- A definir (Divers)'),
  (83, '6- Cartouche'),
  (84, '6- Caisson desenfumage'),
  (85, '6- Treuil Méca.'),
  (86, '6- Treuil Pneu.'),
  (87, '6- Trappe'),
  (88, '6- Coffret Relayage'),
  (89, '7- A definir (Divers)'),
  (90, '7- Destrat Soufflant'),
  (91, '7- Destrat à pale'),
  (92, '8- A definir (Divers)'),
  (93, '8- Monobloc (Positive)'),
  (94, '8- Monobloc (Negative)'),
  (95, '8- UE (Positive)'),
  (96, '8- UE (Negative)'),
  (97, '8- Evapo (Positive)'),
  (98, '8- Evapo (Negative)'),
  (99, '8- Vitrine'),
  (100, '9- A definir (Divers)'),
  (101, '9- Pompe'),
  (102, '10- A definir (Divers)'),
  (103, '10- Regul')
) as t(code, libelle)
on conflict (code) do nothing;

-- Panne. famille = préfixe du libellé avant le premier "-". Codes 47..50 (NULL en source) ignorés.
-- Code 41 (NULL en source) conservé avec le libellé "Non renseignée" (pas de "-" : famille corrigée à null ensuite).
insert into public.pannes (code, libelle, famille)
select code, libelle, nullif(trim(split_part(libelle, '-', 1)), '')
from (values
  (1, 'Clim- Recherche de fuite (FF)'),
  (2, 'Clim- Compresseur HS'),
  (3, 'Clim- Organes Frigo defaillant'),
  (4, 'Clim- Organes Frigo HS'),
  (5, 'Clim- Organe interne GE (Sonde,moteur,volute…)'),
  (6, 'Clim- Organe interne UI  (Sonde,moteur,volute…)'),
  (7, 'Clim- Carte electronique HS GE'),
  (8, 'Clim- Carte electronique HS UI'),
  (9, 'Clim- Telecommande HS'),
  (10, 'Clim- Manque d''entretien'),
  (11, 'Clim- Manque de puissance'),
  (12, 'Clim- Mauvaise utilisation'),
  (13, 'Clim- Filtre à remplacer'),
  (14, 'Clim- Pb Electrique (Cable coupé,non alimenté…)'),
  (15, 'Clim- Fuite de condensats'),
  (16, 'Clim- Inter de proximité HS'),
  (17, 'Clim- Z- Autre'),
  (18, 'VMC- Caisson HS'),
  (19, 'VMC- Manque de débit d''air'),
  (20, 'VMC- Pb Electrique (Cable coupé,non alimenté…)'),
  (21, 'VMC- Gaine arrachées/Non raccordée/Decrochée'),
  (22, 'VMC- Z- Autre'),
  (23, 'RAC- RAC HS'),
  (24, 'RAC- Resistance HS'),
  (25, 'RAC- Pb Electrique (Cable coupé,non alimenté…)'),
  (26, 'RAC- Klixon enclenché'),
  (27, 'RAC- Klixon HS'),
  (28, 'RAC- Pb ventilation (Moteur/Volute)'),
  (29, 'RAC- Pb Telecommande'),
  (30, 'Destrat- Destrat HS'),
  (31, 'Destrat- Pb Electrique (Cable coupé,non alimenté…)'),
  (32, 'Destrat-  Pb Telecommande'),
  (34, 'Chambre froide- CF pas en temperature'),
  (35, 'Chambre froide- Organe Frigo HS'),
  (36, 'Chambre froide- Organe electrique HS'),
  (37, 'Chambre froide- Pb Electrique'),
  (38, 'Chambre froide- Pb Regulation'),
  (39, 'Chambre froide- Porte ouverte'),
  (40, 'Chambre froide- fuite condensats'),
  (41, 'Non renseignée'),
  (42, 'Chaufferie- A completer'),
  (43, 'Chaudieres- A completer'),
  (44, 'Extracteur Labo- A completer'),
  (45, 'Plomberie- A completer'),
  (46, 'Ballon ECS- A completer')
) as t(code, libelle)
on conflict (code) do nothing;

update public.pannes set famille = null where code = 41;
